version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      day: "sunday"
      time: "22:59"
    # Dependabot only bumps packages that are pinned.
    # We pin matplotlib so we’ll get daily PRs for it.
    allow:
      - dependency-name: "matplotlib"
      - dependency-name: "teachbooks"
      - dependency-name: "jupyterbook-patches"
    ignore:
      # These often require specific combos in the Jupyter/Sphinx stack.
      - dependency-name: "sphinx-thebe"
      - dependency-name: "docutils"
