title: CSE 4/573 - Computer Vision and Image Processing
author: Naresh Devulapally, Summer 2025, UB. Built with Teachbooks.

execute:
  execute_notebooks: "off"

only_build_toc_files: false

html:
  favicon: "figures/TB_favicon.ico"
  baseurl: "https://naresh-ub.github.io/cvip"
  extra_css: ["_static/color.css"]
  extra_js: ["_static/analytics.js"]
  analytics:
    google_analytics_id: G-YTF2311PDM

# ✅ Thebe button must be at top-level (not under sphinx:)
launch_buttons:
  thebe: true
  colab_url: "https://colab.research.google.com"

sphinx:
  extra_extensions:
    - sphinx_thebe                # ✅ load upstream extension explicitly
    - sphinx.ext.imgconverter
    - jupyterbook_patches
    - download_link_replacer
    - sphinx.ext.extlinks
    - sphinx_image_inverter
    - sphinx_iframes
    - sphinx_exercise
    - teachbooks_sphinx_tippy
    - sphinx_named_colors
    - sphinx_accessibility

  config:
    # ✅ Load Pyodide 0.29 (Matplotlib 3.8.4) BEFORE Thebe init
    html_js_files:
      - https://cdn.jsdelivr.net/pyodide/v0.29.0/full/pyodide.js?v=2025-10-23
      - https://unpkg.com/thebe-lite@latest/dist/thebe-lite.min.js
      - https://unpkg.com/thebe@latest/dist/lib/index.js
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

    # ✅ Tell sphinx-thebe to use the in-browser (Pyodide) kernel
    thebe_config:
      use_thebe_lite: true
      requestKernel: true
      kernelName: "python"
      selector: ".cell"          # change if your code blocks use a different class
      preexecute: ["thebe-init"]
      exclude_patterns:
        - "**/_*.yml"
        - "**/*.md"
        - "**/*.ipynb"

    html_theme_options:
      logo:
        text: CSE 4/573 - CVIP
        image_light: figures/logo.png
        image_dark: figures/logo_dark.png
      repository_url: "https://github.com/naresh-ub/cvip"
      path_to_docs: "book"
      repository_branch: "main"
      use_edit_page_button: false
      use_repository_button: true
      use_issues_button: false

    html_static_path: ["figures"]
    html_last_updated_fmt: "%B %-d, %Y"
