title: CSE 4/573 - Computer Vision and Image Processing
author: Naresh Devulapally, Summer 2025, UB. Built with Teachbooks.

execute:
  execute_notebooks: "off"

only_build_toc_files: false

# --- Single html: block (merged; you had two)
html:
  favicon: "figures/TB_favicon.ico"
  baseurl: "https://naresh-ub.github.io/cvip"
  extra_css: ["_static/color.css"]
  extra_js: ["_static/analytics.js"]
  analytics:
    google_analytics_id: G-YTF2311PDM

# --- Thebe (lite) + Pyodide 0.29 wiring lives under sphinx.config
sphinx:
  config:
    # Load Pyodide 0.29.0 *before* thebe/thebe-lite so the kernel uses 0.29’s packages.
    # The ?v=… busts browser/CDN cache after deploy.
    html_js_files:
      - https://cdn.jsdelivr.net/pyodide/v0.29.0/full/pyodide.js?v=2025-10-23
      - https://unpkg.com/thebe-lite@latest/dist/thebe-lite.min.js
      - https://unpkg.com/thebe@latest/dist/lib/index.js
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

    # thebe configuration for LITE (Pyodide) runtime
    thebe_config:
      use_thebe_lite: true          # <- force in-browser (Pyodide) kernel, not Binder
      requestKernel: true
      kernelName: "python"
      selector: ".cell"             # adapt to your site; jupyter-book often uses .cell or .thebe
      preexecute: ["thebe-init"]    # auto-run cells tagged thebe-init
      # You can also exclude patterns if needed:
      exclude_patterns:
        - "**/_*.yml"
        - "**/*.md"
        - "**/*.ipynb"

    # Theme + repo buttons (kept from your original)
    html_theme_options:
      logo:
        text: CSE 4/573 - CVIP
        image_light: figures/logo.png
        image_dark: figures/logo_dark.png
      repository_url: "https://github.com/naresh-ub/cvip"
      path_to_docs: "book"
      repository_branch: "main"
      use_edit_page_button: false
      use_repository_button: true
      use_issues_button: false

    # Footer + static paths
    html_show_copyright: false
    html_last_updated_fmt: "%B %-d, %Y"
    html_static_path: ["figures"]

    # MathJax
    mathjax3_config:
      chtml:
        mtextInheritFont: true

  # Sphinx extensions (unchanged)
  extra_extensions:
    - sphinx.ext.imgconverter
    - jupyterbook_patches
    - download_link_replacer
    - sphinx.ext.extlinks
    - sphinx_image_inverter
    - sphinx_iframes
    - sphinx_exercise
    - teachbooks_sphinx_tippy
    - sphinx_named_colors
    - sphinx_accessibility

# Jupyter Book “Launch” UI (keep the Thebe button visible)
launch_buttons:
  thebe: true
  colab_url: "https://colab.research.google.com"

bibtex_bibfiles:
  - references.bib
