title: CSE 4/573 - Computer Vision and Image Processing
author: Naresh Devulapally, Summer 2025, UB. Built with Teachbooks.

execute:
  execute_notebooks: "off"

only_build_toc_files: false

# ---- ONE html block only ----
html:
  favicon: "figures/TB_favicon.ico"
  # Project Pages baseurl must include /cvip/ (trailing slash optional)
  baseurl: "https://naresh-ub.github.io/cvip/"

  extra_css:
    - "_static/color.css"
  extra_js:
    - "_static/analytics.js"

  analytics:
    google_analytics_id: "G-YTF2311PDM"

  # The button appears because launch_buttons.thebe=true
  html_theme_options:
    logo:
      text: "CSE 4/573 - CVIP"
      image_light: "figures/logo.png"
      image_dark: "figures/logo_dark.png"
    repository_url: "https://github.com/naresh-ub/cvip"
    path_to_docs: "book"
    repository_branch: "main"
    use_edit_page_button: false
    use_repository_button: true
    use_issues_button: false
    launch_buttons:
      thebe: true         # <-- THIS shows the Thebe (rocket) button
      colab_url: "https://colab.research.google.com"

  html_show_copyright: false
  html_last_updated_fmt: "%B %-d, %Y"
  html_static_path:
    - "figures"          # existing figures
    - "_static"          # ensure our JS/wheels are copied

# ---- Sphinx config & extensions ----
sphinx:
  config:
    # load RequireJS (as before) + our thebe-init.js loader
    html_js_files:
      - "https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js"
      - "_static/js/thebe-init.js"

    # JupyterLite/Thebe-Lite runtime configuration (NO Binder)
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
      preexecute: ["thebe-init"]

      # These keys instruct Thebe-Lite (JupyterLite) to pin Pyodide
      # and look for vendored pure-Python wheels. They are passed through
      # by the Sphinx-Thebe integration.
      requestKernel: true
      useJupyterLite: true
      litePluginSettings:
        # Pin the exact Pyodide build -> pins core compiled packages (numpy/matplotlib/micropip)
        pyodideUrl: "https://cdn.jsdelivr.net/pyodide/v0.29.0/full/"

      # piplite will fetch wheels from here first (fast & deterministic)
      pipliteUrls:
        - "_static/wheels/"

    mathjax3_config:
      chtml:
        mtextInheritFont: true

  extra_extensions:
    - sphinx.ext.imgconverter
    - jupyterbook_patches
    - download_link_replacer
    - sphinx.ext.extlinks
    - sphinx_image_inverter
    - sphinx_iframes
    - sphinx_exercise
    - sphinx_named_colors
    - sphinx_accessibility
    - teachbooks_sphinx_tippy

bibtex_bibfiles:
  - references.bib
